
title: Home | Bhargav Kadupukutla
name: Bhargav Kadupukutla
email: balu.bhargav186@gmail.com
description: Code. Books. Music.
<<<<<<< HEAD
baseurl:   # the subpath of your site, e.g. /blog
=======
baseurl: # the subpath of your site, e.g. /blog
>>>>>>> 87dd72f0912cbf2890bd66956519b3ea82c9f8f9
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _3hargav0_
github_username:  3hargav
markdown: kramdown


# Build settings
theme: minima
plugins:
  - jekyll-feed
  
